In [2]:
from keras.models import Sequential
from keras.layers import Dense, LSTM
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Paso 1: Preprocesamiento de datos (ejemplo)
# Supongamos que tenemos la siguiente serie de tiempo de prueba
time_series = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13 ,14, 15])
print("time_series: ", time_series)
train_size = int(0.6 * len(time_series)) # Tamaño del entrenamiento
train_data, test_data = time_series[:train_size], time_series[train_size:]
print("train_data: ", train_data)
print("test_data: ", test_data)

time_series:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
train_data:  [1 2 3 4 5 6 7 8 9]
test_data:  [10 11 12 13 14 15]


In [4]:
# Paso 2: Preparación de datos (ejemplo)
# Transformación de los datos de la secuencia
def create_dataset(data, seq_length):
    X, y = [], []
    for i in range(len(data) - seq_length):
        X.append(data[i:i + seq_length])
        y.append(data[i + seq_length])
    return np.array(X), np.array(y)

# Se definen los pasos de tiempo para la serie temporal
seq_length = 4

# Creación del entrenamiento y prueba en 3D
X_train, y_train = create_dataset(train_data, seq_length)
X_test, y_test = create_dataset(test_data, seq_length)

# Se imprimen los conjuntos en 3D
print("X_train: ", X_train)
print("y_train: ", y_train)
print("X_test: ", X_test)
print("y_test: ", y_test)

X_train:  [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]
 [5 6 7 8]]
y_train:  [5 6 7 8 9]
X_test:  [[10 11 12 13]
 [11 12 13 14]]
y_test:  [14 15]


In [5]:
# Paso 3: Construcción del modelo LSTM
model = Sequential()
model.add(LSTM(16, activation='relu', input_shape=(seq_length, 1)))
model.add(Dense(1))

# Paso 4: Compilación
model.compile(loss='mean_squared_error', optimizer='adam')

/usr/local/lib/python3.10/dist-packages/keras/src/layers/rnn/rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [ ]:
# Paso 5: Entrenamiento
model.fit(X_train, y_train, epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - loss: 56.9916
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 56.4002
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 55.8138
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 55.2322
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 54.6548
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 54.0822
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 53.5144
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 52.9505
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 52.3908
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 51.8352
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 51.2835
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 50.7341
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 50.1874
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 49.6420
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 49.0988
Epoch 

In [ ]:
# Paso 6: Evaluación
Evaluacion = model.evaluate(X_test, y_test)
print("Evaluacion: ", Evaluacion)

In [8]:
# Paso 7: Predicción
print("X_test", X_test)
print("y_test", y_test)
y_pred = model.predict(X_test)
print("y_pred", y_pred)

X_test [[10 11 12 13]
 [11 12 13 14]]
y_test [14 15]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 280ms/step
y_pred [[10.222587]
 [10.342736]]
