In [5]:
import keras
import tensorflow as tf

In [9]:
frases = [
    'Hola mundo',
    'Hola a todos',
    'Hola a todo el mundo'
]

In [10]:
# Generación del diccionario de tokens
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words = 10)
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print('word_index =', word_index)

word_index = {'hola': 1, 'mundo': 2, 'a': 3, 'todos': 4, 'todo': 5, 'el': 6}


In [13]:
# Generación de una secuencia tokenizada
secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias =', secuencias)

secuencias = [[1, 2], [1, 3, 4], [1, 3, 5, 6, 2]]


In [14]:
# Relleno a longitud uniforme
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias)
print('relleno =\n', relleno)

relleno =
 [[0 0 0 1 2]
 [0 0 1 3 4]
 [1 3 5 6 2]]


In [17]:
frases = [
    'Hola mundo',
    'Hola a todos',
    'Hola a todo el mundo',
    'Buen dia, como estas hoy']

# Generación del diccionario de tokens
tokenizer = tf.keras.preprocessing.text.Tokenizer(num_words = 10, oov_token="<00V>")
tokenizer.fit_on_texts(frases)
word_index = tokenizer.word_index
print('\nword_index =', word_index)

# Generación de una secuencia tokenizada
secuencias = tokenizer.texts_to_sequences(frases)
print('secuencias =', secuencias)

# Relleno a longitud uniforme
relleno = tf.keras.preprocessing.sequence.pad_sequences(secuencias)
print('relleno =\n', relleno)


word_index = {'<00V>': 1, 'hola': 2, 'mundo': 3, 'a': 4, 'todos': 5, 'todo': 6, 'el': 7, 'buen': 8, 'dia': 9, 'como': 10, 'estas': 11, 'hoy': 12}
secuencias = [[2, 3], [2, 4, 5], [2, 4, 6, 7, 3], [8, 9, 1, 1, 1]]
relleno =
 [[0 0 0 2 3]
 [0 0 2 4 5]
 [2 4 6 7 3]
 [8 9 1 1 1]]


In [20]:
# Relleno a longitud uniforme
relleno2 = tf.keras.preprocessing.sequence.pad_sequences(secuencias,
                                                        padding = 'post',
                                                        truncating = 'post')

print('relleno =\n', relleno2)

relleno =
 [[2 3 0 0 0]
 [2 4 5 0 0]
 [2 4 6 7 3]
 [8 9 1 1 1]]
