##Ejemplo de cómo implementar una red neuronal para clasificación

In [10]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [11]:
# Carga de los datos de iris

iris = load_iris()
X = iris.data
y = iris.target

In [12]:
# Exploración de datos

type(iris)
iris.keys()
iris.data
iris.target
iris.target_names
iris.DESCR
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [13]:
# División de datos para el entrenamiento y la prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
# Escalamiento de características para un mejor rendimiento
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [15]:
# Crear una instancia de MPLClassifier
mlp_clf = MLPClassifier(hidden_layer_sizes=(100),
                        activation='relu',
                        solver='adam',
                        max_iter=100,
                        random_state=42,
                        verbose=True)

In [16]:
# Entrenamiento del modelo

mlp_clf.fit(X_train_scaled, y_train)

Iteration 1, loss = 1.16374923
Iteration 2, loss = 1.14090611
Iteration 3, loss = 1.11857816
Iteration 4, loss = 1.09677375
Iteration 5, loss = 1.07547149
Iteration 6, loss = 1.05468504
Iteration 7, loss = 1.03440573
Iteration 8, loss = 1.01462373
Iteration 9, loss = 0.99535820
Iteration 10, loss = 0.97658926
Iteration 11, loss = 0.95833257
Iteration 12, loss = 0.94053852
Iteration 13, loss = 0.92322169
Iteration 14, loss = 0.90638373
Iteration 15, loss = 0.89000670
Iteration 16, loss = 0.87408395
Iteration 17, loss = 0.85861030
Iteration 18, loss = 0.84357120
Iteration 19, loss = 0.82895431
Iteration 20, loss = 0.81476466
Iteration 21, loss = 0.80097410
Iteration 22, loss = 0.78759157
Iteration 23, loss = 0.77460302
Iteration 24, loss = 0.76199129
Iteration 25, loss = 0.74975377
Iteration 26, loss = 0.73786826
Iteration 27, loss = 0.72632581
Iteration 28, loss = 0.71511871
Iteration 29, loss = 0.70424319
Iteration 30, loss = 0.69368183
Iteration 31, loss = 0.68342580
Iteration 32, los

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=100, max_iter=100, random_state=42,
              verbose=True)

In [17]:
# Realizar predicciones en el conjunto de prueba

y_pred = mlp_clf.predict(X_test_scaled)
print(y_test)
print(y_pred)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]
[1 0 2 1 2 0 1 2 1 1 2 0 0 0 0 2 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [18]:
# Calcular la precisión del modelo

accuracy = accuracy_score(y_test, y_pred)
print("Precisión del modelo:", accuracy)

Precisión del modelo: 0.9333333333333333


##Ejemplo básico de cómo implementar una red neuronal para regresión utilizando MLPRegressor de Scikit-learn

In [20]:
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

In [21]:
# Cargar el conjunto de datos de california Housing

housing = fetch_california_housing()
X, y = housing.data, housing.target

In [23]:
# Exploración de datos

type(housing)
housing.keys()
housing.data
housing.target
housing.target_names
housing.DESCR
housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [25]:
# División de los datos en entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [26]:
# Escalar las caracteristicas para mejorar el rendimiento del modelo

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [27]:
# Instancia de MLPRegressor

mlp_reg = MLPRegressor(hidden_layer_sizes=(100, ),
                          activation='relu',
                          solver='adam',
                          max_iter=100,
                          random_state=42,
                          verbose=True)

In [28]:
# Entrenamiento del modelo

mlp_reg.fit(X_train_scaled, y_train)

Iteration 1, loss = 1.62056447
Iteration 2, loss = 0.43678846
Iteration 3, loss = 0.32700527
Iteration 4, loss = 0.28069940
Iteration 5, loss = 0.24814135
Iteration 6, loss = 0.22803342
Iteration 7, loss = 0.21538976
Iteration 8, loss = 0.20787968
Iteration 9, loss = 0.20154389
Iteration 10, loss = 0.19743378
Iteration 11, loss = 0.19321222
Iteration 12, loss = 0.18961729
Iteration 13, loss = 0.18678600
Iteration 14, loss = 0.18383630
Iteration 15, loss = 0.18157601
Iteration 16, loss = 0.17968086
Iteration 17, loss = 0.17775103
Iteration 18, loss = 0.17538371
Iteration 19, loss = 0.17423819
Iteration 20, loss = 0.17407294
Iteration 21, loss = 0.17085613
Iteration 22, loss = 0.16995187
Iteration 23, loss = 0.16823352
Iteration 24, loss = 0.16798530
Iteration 25, loss = 0.16717835
Iteration 26, loss = 0.16566984
Iteration 27, loss = 0.16730781
Iteration 28, loss = 0.16499618
Iteration 29, loss = 0.16261953
Iteration 30, loss = 0.16145474
Iteration 31, loss = 0.16053131
Iteration 32, los

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(max_iter=100, random_state=42, verbose=True)

In [30]:
# Realización de predicción en el conjunto de pruebas

y_pred = mlp_reg.predict(X_test_scaled)
print(y_pred)

[0.36085326 1.24251853 4.64614402 ... 4.81840928 0.79349547 1.71638212]


In [31]:
# Cálculo del mse del modelo

mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.32870115322611493
